// <auto-generated />
using FactElectFixed.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FactElectFixed.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251024062859_RucEmpresa_IndexAdded")]
    partial class RucEmpresa_IndexAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("FactElectFixed.Api.Features.Configuracion.Entities.ConfiguracionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RucEmpresa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RucEmpresa" }, "RucEmpresa")
                        .IsUnique();

                    b.ToTable("Configuraciones");
                });
#pragma warning restore 612, 618
        }
    }
}
